# 文件名建议：zubo_to_m3u_anhui.py
# 放置位置：https://github.com/linyu345/iptv 根目录
# 使用方式：在仓库根目录运行 python zubo_to_m3u_anhui.py

import re
import urllib.request
from datetime import datetime

# ==================== 配置区域 ====================
INPUT_URL = "https://raw.githubusercontent.com/linyu345/2026/refs/heads/main/py/安徽组播/zubo.txt"

OUTPUT_FILE = "安徽电信组播.m3u"

LOGO_BASE = "https://gcore.jsdelivr.net/gh/kenye201/TVlog/img/"
EPG_URL = "https://live.fanmingming.cn/e.xml"

# 想要保留的分类关键词（可按需增加）
TARGET_GROUP_PREFIX = ["安徽电信"]

# ===================================================

def download_txt(url):
    try:
        with urllib.request.urlopen(url) as response:
            content = response.read().decode('utf-8')
        return content.splitlines()
    except Exception as e:
        print(f"下载文件失败: {e}")
        return []

def is_group_line(line):
    return line.strip().startswith('#genre#') or re.match(r'^[^,]+,#genre#', line.strip())

def get_group_name(line):
    line = line.strip()
    if ',#genre#' in line:
        return line.split(',#genre#')[0].strip()
    return ""

def is_target_group(group_name):
    if not group_name:
        return False
    for prefix in TARGET_GROUP_PREFIX:
        if group_name.startswith(prefix):
            return True
    return False

def make_logo_url(channel_name):
    """简单处理频道名 → 台标名（可根据实际情况加强清洗规则）"""
    # 去掉常见后缀/前缀
    name = re.sub(r'(HD|高清|超清|标清|\d+K|4K|\(\d+\))', '', channel_name, flags=re.I)
    name = name.replace("频道", "").replace("台", "").replace("卫视", "").strip()
    return f"{LOGO_BASE}{name}.png"

def main():
    print(f"正在处理: {INPUT_URL}")
    lines = download_txt(INPUT_URL)
    
    if not lines:
        print("文件内容为空或下载失败，退出")
        return

    current_group = ""
    in_target_group = False
    channels = []

    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue

        # 是分组行
        if is_group_line(line):
            current_group = get_group_name(line)
            in_target_group = is_target_group(current_group)
            
            if in_target_group:
                print(f"找到目标分组 → {current_group}")
            continue

        # 普通频道行
        if in_target_group and ',' in line:
            try:
                name, url = [x.strip() for x in line.split(',', 1)]
                if url.startswith(('http', 'rtmp', 'p2p', 'mitv')):
                    channels.append((current_group, name, url))
            except:
                continue

    # 开始生成 m3u 文件内容
    m3u_lines = [
        "#EXTM3U",
        f"#EXTM3U x-tvg-url=\"{EPG_URL}\"",
        f"# Generated by zubo_to_m3u_anhui.py at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "# Only Anhui Telecom groups",
        ""
    ]

    for group, name, url in channels:
        logo = make_logo_url(name)
        m3u_lines.append(f'#EXTINF:-1 tvg-logo="{logo}" tvg-name="{name}" group-title="{group}",{name}')
        m3u_lines.append(url)
        m3u_lines.append("")

    # 写入文件
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(m3u_lines))
        print(f"\n转换完成！已保存为：{OUTPUT_FILE}")
        print(f"共提取 {len(channels)} 个频道")
    except Exception as e:
        print(f"保存文件失败: {e}")

if __name__ == "__main__":
    main()
